server:
  port: 4415
  servlet:
    context-path: /api

spring:
  application:
    name: search-think-demo
  aop:
    auto: true
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/search_think_test?currentSchema=public&stringtype=unspecified&TimeZone=Asia/Shanghai
    username: postgres
    password: ????
    type: com.alibaba.druid.pool.DruidDataSource

  data:
    # redis
    redis:
      host: localhost
      port: 6379
      database: 0
      password: ????
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: bai.demo.**.pojo
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: none
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true


springdoc:
  packages-to-scan: bai.demo
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'all'
      paths-to-match: '/**'
      packages-to-scan: bai.demo.**

# ??
logging:
  config: classpath:/logback-spring.xml